// WHAT IS STREAMING?
// NODE: AN ABSTRACT INTERFACE TO WORK WITH STREAMS

// STREAMING LIKE VIDEO STREAMING NETFLIX | YOUTUBE ?
// YES! BUT ITS LOT MORE THAN THAT

// STREAMING CAN BE DEFINED AS DATA-FLOWING
// GRADUALLY FLOWING OF DATA INSTEAD OF MOVING TO IT ALL AT ONE TIME
// IN CHUNKS | ONE BY ONE

// BY DEFAULT SIZE OF CHUNCK IS 16kB